#include "game/project/GameStarterScaffold.h"

#include <string>
#include <vector>

#include "core/FileSystem.h"
#include "core/Logger.h"

namespace fw {
namespace {

bool WriteIfMissing(const std::string& path,
                    const std::string& contents,
                    StarterScaffoldResult& result) {
    if (FileSystem::Exists(path)) {
        return false;
    }

    if (!FileSystem::WriteTextFile(path, contents)) {
        Logger::Warn("SCAFFOLD", "Failed to create starter content file: " + path);
        return false;
    }

    result.wroteAnyFiles = true;
    result.createdFiles.push_back(path);
    Logger::Info("SCAFFOLD", "Created starter content file: " + path);
    return true;
}

std::string BuildDefaultProjectFile() {
    return
        "# Starter project file generated by the engine.\n"
        "project=starter_open_world\n"
        "display_name=Starter Open World\n"
        "start_scene=open_world_runtime\n"
        "start_region=starter_village\n"
        "starter_template=open_world_starter\n"
        "create_starter_content=true\n"
        "preload=\n";
}

std::string BuildGettingStartedFile() {
    return
        "START HERE\n"
        "==========\n\n"
        "This version is focused on building your game from asset-authored regions instead of hardcoded C++ layouts.\n\n"
        "Edit these files first:\n"
        "  assets/game.project\n"
        "  assets/regions/starter_village.json\n"
        "  assets/regions/starter_forest.json\n"
        "  assets/quests/clear_the_path.quest\n"
        "  assets/npcs/village_elder.npc\n"
        "  assets/items/iron_sword.item\n\n"
        "Region workflow:\n"
        "  1) Copy one of the starter region json files.\n"
        "  2) Change id, displayName, links, and layout data.\n"
        "  3) Add enemies, travel points, gather nodes, and props in the layout section.\n"
        "  4) Set start_region in assets/game.project when you want a different opening area.\n\n"
        "Runtime shortcuts:\n"
        "  E = interact\n"
        "  Left mouse = attack\n"
        "  I = equipment panel\n"
        "  TAB = quest log\n"
        "  F5/F9 = save/load profile\n"
        "  O/P = save/load world state\n"
        "  F6 = create any missing starter files again\n";
}

std::string BuildStarterVillageRegion() {
    return
        "{\n"
        "  \"id\": \"starter_village\",\n"
        "  \"displayName\": \"Starter Village\",\n"
        "  \"scene\": \"starter_village_scene\",\n"
        "  \"description\": \"A safe starting hub with a quest giver, merchant, and the road to the forest.\",\n"
        "  \"ambientMusicId\": \"village_theme\",\n"
        "  \"safeZone\": true,\n"
        "  \"links\": [\n"
        "    { \"targetRegion\": \"starter_forest\", \"anchorId\": \"east_gate\" }\n"
        "  ],\n"
        "  \"layout\": {\n"
        "    \"playerSpawn\": [0.0, 1.0, 0.0],\n"
        "    \"props\": [\n"
        "      { \"type\": \"box\", \"position\": [0.0, 0.5, 0.0], \"size\": [48.0, 1.0, 48.0], \"color\": [94, 126, 86] },\n"
        "      { \"type\": \"box\", \"position\": [-8.0, 2.0, -5.0], \"size\": [6.0, 4.0, 6.0], \"color\": [148, 110, 72] },\n"
        "      { \"type\": \"box\", \"position\": [8.0, 2.0, 4.0], \"size\": [5.0, 4.0, 5.0], \"color\": [138, 102, 64] },\n"
        "      { \"type\": \"cylinder\", \"position\": [3.0, 2.0, -9.0], \"size\": [1.6, 4.0, 1.6], \"color\": [82, 150, 84] }\n"
        "    ],\n"
        "    \"npcSpawns\": [\n"
        "      { \"npcId\": \"village_elder\", \"position\": [2.0, 1.0, -2.0] },\n"
        "      { \"npcId\": \"shopkeeper_mira\", \"position\": [-4.5, 1.0, 2.5] }\n"
        "    ],\n"
        "    \"gatherPoints\": [ [7.5, 1.0, 7.0] ],\n"
        "    \"travelPoints\": [\n"
        "      { \"position\": [18.0, 1.0, 0.0], \"targetRegion\": \"starter_forest\", \"anchorId\": \"east_gate\", \"destinationSpawn\": [-18.0, 1.0, 0.0] }\n"
        "    ],\n"
        "    \"enemySpawns\": []\n"
        "  }\n"
        "}\n";
}

std::string BuildStarterForestRegion() {
    return
        "{\n"
        "  \"id\": \"starter_forest\",\n"
        "  \"displayName\": \"Starter Forest\",\n"
        "  \"scene\": \"starter_forest_scene\",\n"
        "  \"description\": \"The first combat region where the player clears wolves from the road.\",\n"
        "  \"ambientMusicId\": \"forest_theme\",\n"
        "  \"safeZone\": false,\n"
        "  \"links\": [\n"
        "    { \"targetRegion\": \"starter_village\", \"anchorId\": \"west_gate\" }\n"
        "  ],\n"
        "  \"layout\": {\n"
        "    \"playerSpawn\": [-18.0, 1.0, 0.0],\n"
        "    \"props\": [\n"
        "      { \"type\": \"box\", \"position\": [0.0, 0.5, 0.0], \"size\": [72.0, 1.0, 72.0], \"color\": [58, 106, 64] },\n"
        "      { \"type\": \"cylinder\", \"position\": [-10.0, 2.0, -10.0], \"size\": [1.3, 4.0, 1.3], \"color\": [76, 132, 72] },\n"
        "      { \"type\": \"cylinder\", \"position\": [7.0, 2.0, -12.0], \"size\": [1.4, 4.0, 1.4], \"color\": [74, 139, 74] },\n"
        "      { \"type\": \"cylinder\", \"position\": [15.0, 2.0, 8.0], \"size\": [1.2, 4.0, 1.2], \"color\": [72, 134, 72] },\n"
        "      { \"type\": \"box\", \"position\": [4.0, 0.75, 5.0], \"size\": [4.0, 1.5, 4.0], \"color\": [118, 90, 58] }\n"
        "    ],\n"
        "    \"npcSpawns\": [],\n"
        "    \"gatherPoints\": [ [4.0, 1.0, 7.0], [10.0, 1.0, -2.0], [-12.0, 1.0, -4.0] ],\n"
        "    \"travelPoints\": [\n"
        "      { \"position\": [-20.0, 1.0, 0.0], \"targetRegion\": \"starter_village\", \"anchorId\": \"west_gate\", \"destinationSpawn\": [17.0, 1.0, 0.0] }\n"
        "    ],\n"
        "    \"enemySpawns\": [\n"
        "      { \"type\": \"wolf\", \"position\": [8.0, 1.0, 10.0] },\n"
        "      { \"type\": \"wolf\", \"position\": [-10.0, 1.0, -8.0] },\n"
        "      { \"type\": \"wolf\", \"position\": [12.0, 1.0, -11.0] }\n"
        "    ]\n"
        "  }\n"
        "}\n";
}

std::string BuildVillageElderNpc() {
    return
        "id=village_elder\n"
        "displayName=Village Elder\n"
        "regionId=starter_village\n"
        "dialogueId=village_elder_intro\n"
        "questId=clear_the_path\n"
        "factionId=villagers\n"
        "homeRegionId=starter_village\n";
}

std::string BuildMerchantNpc() {
    return
        "id=shopkeeper_mira\n"
        "displayName=Shopkeeper Mira\n"
        "regionId=starter_village\n"
        "dialogueId=shopkeeper_mira_intro\n"
        "factionId=villagers\n"
        "homeRegionId=starter_village\n";
}

std::string BuildVillageElderDialogue() {
    return
        "id=village_elder_intro\n"
        "speakerName=Village Elder\n"
        "text=The road through the forest is unsafe. Clear out the wolves and come back alive.\n";
}

std::string BuildMerchantDialogue() {
    return
        "id=shopkeeper_mira_intro\n"
        "speakerName=Shopkeeper Mira\n"
        "text=Travel prepared. Good gear and a potion make the first adventure much easier.\n";
}

std::string BuildStarterQuest() {
    return
        "id=clear_the_path\n"
        "title=Clear the Path\n"
        "description=Defeat 2 wolves in the starter forest and report back.\n"
        "giverNpcId=village_elder\n"
        "targetEnemyType=wolf\n"
        "targetRegionId=starter_forest\n"
        "targetCount=2\n"
        "rewardItemId=healing_potion\n"
        "rewardGold=40\n";
}

std::string BuildIronSwordItem() {
    return
        "id=iron_sword\n"
        "displayName=Iron Sword\n"
        "type=weapon\n"
        "description=A dependable starter weapon.\n"
        "equipSlot=weapon\n"
        "value=25\n"
        "attack=10\n"
        "defense=0\n"
        "heal=0\n";
}

std::string BuildLeatherArmorItem() {
    return
        "id=leather_armor\n"
        "displayName=Leather Armor\n"
        "type=armor\n"
        "description=Simple armor for a first zone hero.\n"
        "equipSlot=armor\n"
        "value=20\n"
        "attack=0\n"
        "defense=4\n"
        "heal=0\n";
}

std::string BuildHealingPotionItem() {
    return
        "id=healing_potion\n"
        "displayName=Healing Potion\n"
        "type=consumable\n"
        "description=Restores health when used.\n"
        "equipSlot=\n"
        "value=12\n"
        "attack=0\n"
        "defense=0\n"
        "heal=25\n";
}

std::string BuildWolfLootFile() {
    return "id=wolf\n";
}

} // namespace

StarterScaffoldResult GameStarterScaffold::EnsureStarterProject(const std::string& assetsRoot,
                                                                const GameProjectDefinition& project) {
    StarterScaffoldResult result;

    if (!project.createStarterContentIfMissing) {
        return result;
    }

    WriteIfMissing(assetsRoot + "/game.project", BuildDefaultProjectFile(), result);
    WriteIfMissing(assetsRoot + "/START_HERE.txt", BuildGettingStartedFile(), result);

    if (project.starterTemplate != "open_world_starter") {
        return result;
    }

    WriteIfMissing(assetsRoot + "/regions/starter_village.json", BuildStarterVillageRegion(), result);
    WriteIfMissing(assetsRoot + "/regions/starter_forest.json", BuildStarterForestRegion(), result);

    WriteIfMissing(assetsRoot + "/npcs/village_elder.npc", BuildVillageElderNpc(), result);
    WriteIfMissing(assetsRoot + "/npcs/shopkeeper_mira.npc", BuildMerchantNpc(), result);

    WriteIfMissing(assetsRoot + "/dialogue/village_elder_intro.dialogue", BuildVillageElderDialogue(), result);
    WriteIfMissing(assetsRoot + "/dialogue/shopkeeper_mira_intro.dialogue", BuildMerchantDialogue(), result);

    WriteIfMissing(assetsRoot + "/quests/clear_the_path.quest", BuildStarterQuest(), result);

    WriteIfMissing(assetsRoot + "/items/iron_sword.item", BuildIronSwordItem(), result);
    WriteIfMissing(assetsRoot + "/items/leather_armor.item", BuildLeatherArmorItem(), result);
    WriteIfMissing(assetsRoot + "/items/healing_potion.item", BuildHealingPotionItem(), result);

    WriteIfMissing(assetsRoot + "/loot/wolf.loot", BuildWolfLootFile(), result);

    return result;
}

} // namespace fw
