#include "game/project/GameStarterScaffold.h"

#include <string>
#include <vector>

#include "core/FileSystem.h"
#include "core/Logger.h"

namespace fw {
namespace {

bool WriteIfMissing(const std::string& path,
                    const std::string& contents,
                    StarterScaffoldResult& result) {
    if (FileSystem::Exists(path)) {
        return false;
    }

    if (!FileSystem::WriteTextFile(path, contents)) {
        Logger::Warn("SCAFFOLD", "Failed to create starter content file: " + path);
        return false;
    }

    result.wroteAnyFiles = true;
    result.createdFiles.push_back(path);
    Logger::Info("SCAFFOLD", "Created starter content file: " + path);
    return true;
}

std::string BuildDefaultProjectFile() {
    return
        "# Starter project file generated by the engine.\n"
        "project=starter_open_world\n"
        "display_name=Starter Open World\n"
        "start_scene=open_world_runtime\n"
        "start_region=starter_village\n"
        "starter_template=open_world_starter\n"
        "create_starter_content=true\n"
        "preload=\n";
}

std::string BuildGettingStartedFile() {
    return
        "START HERE\n"
        "==========\n\n"
        "This project now supports file-driven region layouts.\n\n"
        "Edit these files first:\n"
        "  assets/game.project\n"
        "  assets/regions/starter_village.json\n"
        "  assets/regions/starter_forest.json\n"
        "  assets/regions/_template_region.json\n"
        "  assets/quests/clear_the_path.quest\n"
        "  assets/npcs/village_elder.npc\n"
        "  assets/items/iron_sword.item\n\n"
        "Fast workflow:\n"
        "  1) Copy _template_region.json to make a new region.\n"
        "  2) Change id and links in the new file.\n"
        "  3) Edit the layout block for spawn points, props, gather nodes, travel, and enemies.\n"
        "  4) Update start_region in assets/game.project.\n"
        "  5) Add matching .npc, .quest, .dialogue, and .item files as needed.\n";
}

std::string BuildStarterVillageRegion() {
    return
        "{\n"
        "  \"id\": \"starter_village\",\n"
        "  \"displayName\": \"Starter Village\",\n"
        "  \"scene\": \"starter_village_scene\",\n"
        "  \"description\": \"The first safe hub for your game.\",\n"
        "  \"ambientMusicId\": \"village_theme\",\n"
        "  \"safeZone\": true,\n"
        "  \"links\": [\n"
        "    { \"targetRegion\": \"starter_forest\", \"anchorId\": \"east_gate\" }\n"
        "  ],\n"
        "  \"layout\": {\n"
        "    \"playerSpawn\": [0, 1, 0],\n"
        "    \"props\": [\n"
        "      { \"type\": \"box\", \"position\": [0, 0.5, 0], \"size\": [48, 1, 48], \"color\": [95, 125, 85, 255] },\n"
        "      { \"type\": \"box\", \"position\": [-7, 2, -5], \"size\": [6, 4, 6], \"color\": [150, 110, 70, 255] },\n"
        "      { \"type\": \"box\", \"position\": [9, 2, 4], \"size\": [5, 4, 5], \"color\": [140, 100, 60, 255] },\n"
        "      { \"type\": \"cylinder\", \"position\": [4, 2, -10], \"size\": [1.5, 4, 1.5], \"color\": [90, 150, 80, 255] }\n"
        "    ],\n"
        "    \"npcSpawns\": [[2, 1, -2], [-5, 1, 3]],\n"
        "    \"gatherPoints\": [[8, 1, 8]],\n"
        "    \"travelPoints\": [[20, 1, 0]],\n"
        "    \"enemySpawns\": []\n"
        "  }\n"
        "}\n";
}

std::string BuildStarterForestRegion() {
    return
        "{\n"
        "  \"id\": \"starter_forest\",\n"
        "  \"displayName\": \"Starter Forest\",\n"
        "  \"scene\": \"starter_forest_scene\",\n"
        "  \"description\": \"Your first combat and quest region.\",\n"
        "  \"ambientMusicId\": \"forest_theme\",\n"
        "  \"safeZone\": false,\n"
        "  \"links\": [\n"
        "    { \"targetRegion\": \"starter_village\", \"anchorId\": \"west_gate\" }\n"
        "  ],\n"
        "  \"layout\": {\n"
        "    \"playerSpawn\": [-18, 1, 0],\n"
        "    \"props\": [\n"
        "      { \"type\": \"box\", \"position\": [0, 0.5, 0], \"size\": [70, 1, 70], \"color\": [55, 105, 60, 255] },\n"
        "      { \"type\": \"cylinder\", \"position\": [-10, 2, -10], \"size\": [1.2, 4, 1.2], \"color\": [80, 130, 70, 255] },\n"
        "      { \"type\": \"cylinder\", \"position\": [6, 2, -14], \"size\": [1.6, 4, 1.6], \"color\": [75, 140, 75, 255] },\n"
        "      { \"type\": \"box\", \"position\": [-4, 0.6, 12], \"size\": [4, 1.2, 3], \"color\": [120, 90, 60, 255] }\n"
        "    ],\n"
        "    \"npcSpawns\": [[-6, 1, 4]],\n"
        "    \"gatherPoints\": [[3, 1, 6], [10, 1, -2], [-12, 1, -4]],\n"
        "    \"travelPoints\": [[-25, 1, 0]],\n"
        "    \"enemySpawns\": [\n"
        "      { \"position\": [8, 1, 10], \"type\": \"wolf\" },\n"
        "      { \"position\": [-10, 1, -8], \"type\": \"wolf\" },\n"
        "      { \"position\": [12, 1, -12], \"type\": \"raider\" }\n"
        "    ]\n"
        "  }\n"
        "}\n";
}

std::string BuildTemplateRegion() {
    return
        "{\n"
        "  \"id\": \"new_region_id\",\n"
        "  \"displayName\": \"New Region\",\n"
        "  \"scene\": \"new_region_scene\",\n"
        "  \"description\": \"Describe this region.\",\n"
        "  \"ambientMusicId\": \"region_theme\",\n"
        "  \"safeZone\": false,\n"
        "  \"links\": [\n"
        "    { \"targetRegion\": \"starter_village\", \"anchorId\": \"return_gate\" }\n"
        "  ],\n"
        "  \"layout\": {\n"
        "    \"playerSpawn\": [0, 1, 0],\n"
        "    \"props\": [\n"
        "      { \"type\": \"box\", \"position\": [0, 0.5, 0], \"size\": [50, 1, 50], \"color\": [100, 120, 100, 255] }\n"
        "    ],\n"
        "    \"npcSpawns\": [[0, 1, 4]],\n"
        "    \"gatherPoints\": [[4, 1, 4]],\n"
        "    \"travelPoints\": [[-20, 1, 0], [20, 1, 0]],\n"
        "    \"enemySpawns\": [\n"
        "      { \"position\": [8, 1, 6], \"type\": \"wolf\" }\n"
        "    ]\n"
        "  }\n"
        "}\n";
}

std::string BuildVillageElderNpc() {
    return
        "id=village_elder\n"
        "displayName=Village Elder\n"
        "regionId=starter_village\n"
        "dialogueId=village_elder_intro\n"
        "questId=clear_the_path\n"
        "factionId=villagers\n"
        "homeRegionId=starter_village\n";
}

std::string BuildMerchantNpc() {
    return
        "id=shopkeeper_mira\n"
        "displayName=Shopkeeper Mira\n"
        "regionId=starter_village\n"
        "dialogueId=shopkeeper_mira_intro\n"
        "factionId=villagers\n"
        "homeRegionId=starter_village\n";
}

std::string BuildVillageElderDialogue() {
    return
        "id=village_elder_intro\n"
        "speakerName=Village Elder\n"
        "text=The road through the forest is unsafe. Clear out the wolves and come back alive.\n";
}

std::string BuildMerchantDialogue() {
    return
        "id=shopkeeper_mira_intro\n"
        "speakerName=Shopkeeper Mira\n"
        "text=Travel prepared. Good gear and a potion make the first adventure much easier.\n";
}

std::string BuildStarterQuest() {
    return
        "id=clear_the_path\n"
        "title=Clear the Path\n"
        "description=Defeat 2 wolves in the starter forest and report back.\n"
        "giverNpcId=village_elder\n"
        "targetEnemyType=wolf\n"
        "targetRegionId=starter_forest\n"
        "targetCount=2\n"
        "rewardItemId=healing_potion\n"
        "rewardGold=40\n";
}

std::string BuildIronSwordItem() {
    return
        "id=iron_sword\n"
        "displayName=Iron Sword\n"
        "type=weapon\n"
        "description=A dependable starter weapon.\n"
        "equipSlot=weapon\n"
        "value=25\n"
        "attack=10\n"
        "defense=0\n"
        "heal=0\n";
}

std::string BuildLeatherArmorItem() {
    return
        "id=leather_armor\n"
        "displayName=Leather Armor\n"
        "type=armor\n"
        "description=Simple armor for a first zone hero.\n"
        "equipSlot=armor\n"
        "value=20\n"
        "attack=0\n"
        "defense=4\n"
        "heal=0\n";
}

std::string BuildHealingPotionItem() {
    return
        "id=healing_potion\n"
        "displayName=Healing Potion\n"
        "type=consumable\n"
        "description=Restores health when used.\n"
        "equipSlot=\n"
        "value=12\n"
        "attack=0\n"
        "defense=0\n"
        "heal=25\n";
}

std::string BuildWolfLootFile() {
    return "id=wolf\n";
}

} // namespace

StarterScaffoldResult GameStarterScaffold::EnsureStarterProject(const std::string& assetsRoot,
                                                                const GameProjectDefinition& project) {
    StarterScaffoldResult result;

    if (!project.createStarterContentIfMissing) {
        return result;
    }

    WriteIfMissing(assetsRoot + "/game.project", BuildDefaultProjectFile(), result);
    WriteIfMissing(assetsRoot + "/START_HERE.txt", BuildGettingStartedFile(), result);

    if (project.starterTemplate != "open_world_starter") {
        return result;
    }

    WriteIfMissing(assetsRoot + "/regions/starter_village.json", BuildStarterVillageRegion(), result);
    WriteIfMissing(assetsRoot + "/regions/starter_forest.json", BuildStarterForestRegion(), result);

    WriteIfMissing(assetsRoot + "/regions/_template_region.json", BuildTemplateRegion(), result);

    WriteIfMissing(assetsRoot + "/npcs/village_elder.npc", BuildVillageElderNpc(), result);
    WriteIfMissing(assetsRoot + "/npcs/shopkeeper_mira.npc", BuildMerchantNpc(), result);

    WriteIfMissing(assetsRoot + "/dialogue/village_elder_intro.dialogue", BuildVillageElderDialogue(), result);
    WriteIfMissing(assetsRoot + "/dialogue/shopkeeper_mira_intro.dialogue", BuildMerchantDialogue(), result);

    WriteIfMissing(assetsRoot + "/quests/clear_the_path.quest", BuildStarterQuest(), result);

    WriteIfMissing(assetsRoot + "/items/iron_sword.item", BuildIronSwordItem(), result);
    WriteIfMissing(assetsRoot + "/items/leather_armor.item", BuildLeatherArmorItem(), result);
    WriteIfMissing(assetsRoot + "/items/healing_potion.item", BuildHealingPotionItem(), result);

    WriteIfMissing(assetsRoot + "/loot/wolf.loot", BuildWolfLootFile(), result);

    return result;
}

} // namespace fw
